// tests/shooter_arena.rs — headless coverage for the top-down shooter demo
// (shooter/arena.level, generated by ember2d/examples/gen_shooter.rs).
//
// ── WHY THIS EXISTS SEPARATELY FROM tests/common/mod.rs ──────────────────────
//
// `TurnHarness` drives a TurnBased simulation: it gates the late phase on
// `turn_triggered` and never integrates physics at all (the D7 fix, Step 5f).
// A realtime game is the opposite on both counts — physics integrates every
// step and the late phase always runs — so this file carries its own small
// driver rather than adding a mode flag to a harness whose entire value is
// being the single, unambiguous copy of the turn sequence. This driver mirrors
// `ember2d::sim::step`'s `gate_late_phase_on_turn: false` branch; if that
// sequence ever changes, this must change with it.
//
// ── WHAT THIS IS ACTUALLY GUARDING ──────────────────────────────────────────
//
// The demo is ~600 lines of Rhai, and a Rhai mistake is a *runtime* error: the
// script logs an error, `ScriptEngine` adds it to `disabled_scripts`, and the
// game silently continues with that entity doing nothing forever. Nothing
// about that fails a build. `assert_no_script_errors` is therefore the single
// most valuable assertion here — a typo'd function name or an int/float
// mismatch anywhere in either script surfaces as a test failure instead of as
// a demo that quietly stops spawning enemies.

use std::collections::{BTreeMap, BTreeSet};

use ember2d::prelude::*;
use ember2d_sim::command::{GamepadSnapshot, InputSnapshot, MouseSnapshot};
use ember2d_sim::components::{Collider, Tag};
use ember2d_sim::scripting::{LogEntry, LogLevel};
use ember2d_sim::simulation::{Simulation, StepInput};

const DT: f32 = 1.0 / 60.0;
const LEVEL: &str = "shooter/arena.level";

/// See `tests/common/mod.rs`'s copy of this — `cargo test` runs each test
/// binary with CWD set to the package directory (`ember2d/`), one level below
/// the repo root, which breaks both the level path and the repo-root-relative
/// `script` paths inside the level file.
fn ensure_workspace_root_cwd() {
    let _ = std::env::set_current_dir(concat!(env!("CARGO_MANIFEST_DIR"), "/.."));
}

struct RealtimeHarness {
    world: World,
    sim: Simulation,
    persistent: BTreeMap<String, rhai::Dynamic>,
    elapsed: f32,
    logs: Vec<LogEntry>,
}

impl RealtimeHarness {
    fn load() -> Self {
        ensure_workspace_root_cwd();
        let data = LevelData::load(LEVEL).unwrap_or_else(|e| panic!("load {}: {}", LEVEL, e));
        let mut world = World::new();
        let mut persistent = BTreeMap::new();
        let mut sim = Simulation::new(data);
        sim.on_start(&mut world, 80, 24, &mut persistent);
        RealtimeHarness { world, sim, persistent, elapsed: 0.0, logs: Vec::new() }
    }

    /// One realtime step: `Simulation::step`, then unconditionally integrate
    /// physics, detect collisions and `late_step`. `held` is the set of keys
    /// down this step; they're reported as both held and pressed, which is
    /// what a synthetic one-step tap looks like to `is_held`/`just_pressed`.
    ///
    /// `camera_origin` is always `Vec2::ZERO` here (this harness never moves
    /// a camera), so `get_mouse_world_x/y` — mouse cell plus camera origin —
    /// equal `mouse.cell` exactly. A test that wants the player to aim at a
    /// specific world point can hand that point straight to `mouse.cell`.
    fn step(&mut self, held: &[&str]) {
        self.step_with_mouse(held, MouseSnapshot::default());
    }

    fn step_with_mouse(&mut self, held: &[&str], mouse: MouseSnapshot) {
        let prev_positions = self.world.snapshot_positions();

        let keys: BTreeSet<String> = held.iter().map(|k| k.to_string()).collect();
        let input = InputSnapshot { held: keys.clone(), pressed: keys };

        let outcome = self.sim.step(&mut self.world, StepInput {
            input: &input,
            mouse,
            gamepad: &GamepadSnapshot::default(),
            external_commands: &[],
            camera_origin: Vec2::ZERO,
            sim_dt: DT,
            elapsed: self.elapsed,
            viewport_w: 80,
            viewport_h: 24,
        }, &mut self.persistent);
        self.logs.extend(outcome.logs);

        self.world.integrate_physics(DT);
        let mut events = EventBus::new();
        self.world.detect_collisions(&mut events);
        let late = self.sim.late_step(
            &mut self.world, &events, &prev_positions, Vec2::ZERO,
            DT, self.elapsed, 80, 24, &mut self.persistent,
        );
        self.logs.extend(late.logs);

        self.elapsed += DT;
    }

    fn run(&mut self, steps: usize, held: &[&str]) {
        for _ in 0..steps {
            self.step(held);
        }
    }

    /// `run`, but firing left-click at a fixed world-space aim point every
    /// step — `player.rhai`'s cooldown (not the caller) is what actually
    /// paces the resulting shots.
    fn run_firing_at(&mut self, steps: usize, held: &[&str], aim: (f32, f32)) {
        let mouse = MouseSnapshot { cell: aim, held: (true, false), pressed: (true, false) };
        for _ in 0..steps {
            self.step_with_mouse(held, mouse);
        }
    }

    fn count_tag(&self, tag: &str) -> usize {
        self.world.tags.values().filter(|t| t.name == tag).count()
    }

    fn first_tagged(&self, tag: &str) -> Option<EntityId> {
        self.world.tags.iter().find(|(_, t)| t.name == tag).map(|(&id, _)| id)
    }

    /// A script error means `ScriptEngine` disabled that script — the demo
    /// would keep running with a dead director or a dead player controller and
    /// never say so. Always assert this, in every test.
    fn assert_no_script_errors(&self) {
        let errors: Vec<&str> = self.logs.iter()
            .filter(|l| l.level == LogLevel::Error)
            .map(|l| l.text.as_str())
            .collect();
        assert!(errors.is_empty(), "scripts logged errors: {:#?}", errors);
    }
}

/// Wave 1 begins `intro_delay()` (3.0s) after the director arms its countdown
/// on the first step, so 3.5s of steps clears it with margin.
const STEPS_PAST_FIRST_WAVE: usize = 210;

#[test]
fn the_arena_loads_with_a_player_a_director_and_an_intact_wall_ring() {
    let h = RealtimeHarness::load();

    assert_eq!(h.count_tag("player"), 1, "exactly one player should spawn");
    assert_eq!(h.count_tag("director"), 1, "exactly one director should spawn");

    // 80x24 perimeter: 2*80 top/bottom + 2*22 sides, plus six 4x2 cover
    // blocks. A gap here would let the player (the one entity the engine's
    // solid resolver acts on) walk out of the arena.
    assert_eq!(h.count_tag("wall"), 2 * 80 + 2 * 22 + 6 * 8);
}

#[test]
fn the_first_wave_spawns_after_the_intro_countdown_and_not_before() {
    let mut h = RealtimeHarness::load();

    // Half a second in, the countdown is still running.
    h.run(30, &[]);
    h.assert_no_script_errors();
    assert_eq!(h.count_tag("grunt"), 0, "no enemies until the countdown ends");

    h.run(STEPS_PAST_FIRST_WAVE - 30, &[]);
    h.assert_no_script_errors();

    // Wave 1 is grunts only (director.rhai's wave table).
    assert_eq!(h.count_tag("grunt"), 4, "wave 1 should spawn exactly 4 grunts");
    assert_eq!(h.count_tag("swarmer"), 0);
    assert_eq!(h.count_tag("brute"), 0);
}

#[test]
fn holding_left_click_aims_at_the_mouse_and_fires_bullets_that_expire_against_the_wall() {
    let mut h = RealtimeHarness::load();
    h.run(30, &[]);

    // Aim due right of the player's (40, 12) spawn and hold left-click for
    // half a second. The cooldown is 0.16s, so this is ~3 shots; each must
    // exist as a real entity with a velocity.
    h.run_firing_at(30, &[], (78.0, 12.0));
    h.assert_no_script_errors();
    let in_flight = h.count_tag("bullet");
    assert!(in_flight > 0, "holding left-click should spawn bullets");

    // Stop firing and let them cross the arena. The player spawns at x=40 and
    // the wall is at x=79, so at 30 cells/s every bullet reaches it well
    // inside 2 seconds — and director.rhai, not the engine, is what has to
    // notice and destroy them.
    h.run(120, &[]);
    h.assert_no_script_errors();
    assert_eq!(h.count_tag("bullet"), 0, "bullets must be destroyed on hitting a wall");
}

#[test]
fn the_cursor_sitting_on_the_player_fires_no_bullet() {
    let mut h = RealtimeHarness::load();
    h.run(30, &[]);

    let player = h.first_tagged("player").expect("player");
    let pos = h.world.get_global_position(player);

    // Aim exactly at the player's own position — `do_shoot`'s
    // `min_aim_dist_sq` guard should refuse to fire rather than normalise a
    // near-zero direction vector.
    h.run_firing_at(20, &[], (pos.x, pos.y));
    h.assert_no_script_errors();
    assert_eq!(h.count_tag("bullet"), 0, "aiming at the player's own position should not fire");
}

#[test]
fn two_bullets_landing_in_one_pass_both_count_against_an_enemy() {
    let mut h = RealtimeHarness::load();
    h.run(STEPS_PAST_FIRST_WAVE, &[]);
    h.assert_no_script_errors();

    let grunt = h.first_tagged("grunt").expect("wave 1 should have spawned grunts");
    let pos = h.world.transforms[&grunt].position;

    // Two bullets stacked on the grunt in the SAME step. A grunt has 2 HP, so
    // it only dies if `resolve_hits` tallies both hits before writing — which
    // is the whole reason that function counts duplicates instead of doing a
    // read-modify-write per hit. Resolving them one at a time would apply 1
    // damage total (both reads see the same pre-pass value, last write wins)
    // and this assertion would fail.
    for _ in 0..2 {
        let b = h.world.spawn();
        h.world.add_transform(b, Transform::new(pos.x, pos.y));
        h.world.add_collider(b, Collider::trigger(0.4, 0.4));
        h.world.add_tag(b, Tag::new("bullet"));
    }

    h.step(&[]);
    h.assert_no_script_errors();

    assert!(
        !h.world.transforms.contains_key(&grunt),
        "a 2 HP grunt should die to two bullets landing in the same pass"
    );
    assert_eq!(h.count_tag("grunt"), 3, "only the struck grunt should have died");
}

#[test]
fn all_ten_waves_run_in_order_and_then_the_run_is_won() {
    let mut h = RealtimeHarness::load();

    // Fast-forward by clearing each wave the instant it lands, so this covers
    // the whole progression in a couple of thousand steps instead of however
    // long it would take to actually shoot ~120 enemies.
    //
    // The wave table is indexed `t[wave - 1]`, so the single most likely bug
    // in the state machine is an off-by-one that asks for wave 11 and reads
    // past the end of a 10-element array — which in Rhai is a runtime error,
    // caught here by `assert_no_script_errors` rather than by the compiler.
    let mut waves_seen = 0;
    let mut in_wave = false;

    // 3s intro + 10 waves x 3s breather = 33s, plus margin.
    for _ in 0..2400 {
        h.step(&[]);

        let live: Vec<EntityId> = h.world.tags.iter()
            .filter(|(_, t)| t.name == "grunt" || t.name == "swarmer" || t.name == "brute")
            .map(|(&id, _)| id)
            .collect();

        if live.is_empty() {
            in_wave = false;
            continue;
        }
        if !in_wave {
            waves_seen += 1;
            in_wave = true;
        }
        for id in live {
            h.world.despawn(id);
        }
    }

    h.assert_no_script_errors();
    assert_eq!(waves_seen, 10, "exactly ten waves should spawn, then no more");
}

#[test]
fn a_long_run_under_continuous_input_never_errors() {
    let mut h = RealtimeHarness::load();

    // ~17 seconds of play with the player pinned against constant movement and
    // held left-click, aimed at a fixed point off to one side so shots keep
    // firing regardless of which direction the player is currently walking.
    // Long enough to cover the intro, all of wave 1, the kill path, medkit
    // drops, the breather, and the start of wave 2 — i.e. every branch of the
    // director's state machine except the win condition.
    for _ in 0..10 {
        h.run_firing_at(50, &["d"], (78.0, 12.0));
        h.run_firing_at(50, &["s"], (78.0, 12.0));
        h.run_firing_at(50, &["a"], (78.0, 12.0));
        h.run_firing_at(50, &["w"], (78.0, 12.0));
    }
    h.assert_no_script_errors();

    // The player is the only entity the engine's solid resolver acts on, so
    // driving into a wall for seconds at a time must not push it through one.
    let p = h.world.get_global_position(h.first_tagged("player").expect("player"));
    assert!(p.x > 0.0 && p.x < 79.0 && p.y > 0.0 && p.y < 23.0, "player escaped the arena at {:?}", p);
}
